13 add send message
massalabs/massa-sc-std pull request #14
Opened 2022-03-15 11:14 UTC by Eitu33

https://github.com/massalabs/massa-sc-std/issues/13

2022-03-15 15:02 UTC, AurelienFT commented on assembly/index.ts
> +export declare function assembly_script_send_message(target_address: string, target_handler: string,validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thre
```suggestion
export declare function assembly_script_send_message(target_address: string, target_handler: string, validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thread: i64, max_gas: u64, gas_price: string, coins: string, payload: string): void;
```
Also, why `validity_start_period:`, `validity_start_thread`, `validity_end_period` and `validity_end_thread` are `i64` ? Why reading their name it don't seems they could be negative

2022-03-15 19:33 UTC, damip requested changes

2022-03-15 19:33 UTC, damip commented on assembly/index.ts
> +export declare function assembly_script_send_message(target_address: string, target_handler: string,validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thre
let's rename "payload" into "data"

2022-03-15 19:33 UTC, damip commented on assembly/index.ts
> + * @param payload Message payload
payload => data

2022-03-15 19:33 UTC, damip commented on assembly/index.ts
> +export function send_message(target_address: string, target_handler: string, validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thread: i64, max_gas: u64,
maybe the tuples can be represented in a more idiomatic and compact way in assemblyscript, so that the usage of this wrapper makes it simpler to emit messages

2022-03-15 19:33 UTC, damip commented on assembly/index.ts
> +export function send_message(target_address: string, target_handler: string, validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thread: i64, max_gas: u64,
payload => data

2022-03-15 19:33 UTC, damip commented on assembly/index.ts
> +export declare function assembly_script_send_message(target_address: string, target_handler: string,validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thre
https://www.assemblyscript.org/types.html

good catch, they should be positive. Also the "thread" should be represented as an i32 in the ABI and as u8 in assemblyscript

2022-03-16 09:57 UTC, Eitu33 commented on assembly/index.ts
> +export function send_message(target_address: string, target_handler: string, validity_start_period: i64, validity_start_thread: i64, validity_end_period: i64, validity_end_thread: i64, max_gas: u64,
I tried using tuples but their are not yet implemented for AS: https://github.com/AssemblyScript/assemblyscript/issues/1633#issuecomment-766480528

2022-03-16 10:23 UTC, AurelienFT approved these changes
Good for me !

2022-03-16 10:39 UTC, damip requested changes

2022-03-16 10:39 UTC, damip commented on assembly/index.ts
> +export function send_message(target_address: string, target_handler: string, validity_start_period: u64, validity_start_thread: u8, validity_end_period: u64, validity_end_thread: u8, max_gas: u64, ga
gas_price and coins should be u64 raw coins (see how it's done elsewhere)

2022-03-16 11:10 UTC, damip approved these changes

2022-03-16 11:14 UTC, merged